### ISSUE TITLE
Make this repository a template

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey-community/chocolatey-packages-template#31]
GitHub released [a new feature](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/) this year that we can check a box and make this repository a template repository. Perfect fit for this repository!

**Comment by timkatje** [comment]
I second this request, and am surprised that it's been open for this long.  It's a simple check box.  There are several advantages to listing this repo as a template.  Per GitHub's own documentation:
>Creating a repository from a template is similar to forking a repository, but there are important differences:
  *A new fork includes the entire commit history of the parent repository, while a repository created from a template starts with a single commit.
  *Commits to a fork don't appear in your contributions graph, while commits to a repository created from a template do appear in your contribution graph.
  *A fork can be a temporary way to contribute code to an existing project, while creating a repository from a template starts a new project quickly.

I think the second bullet point is critical here. If we're forking chocolatey's repo to create our own packages, our commits to _our_ projects don't appear in our contributions graph, even though we are doing the work of creating/maintaining our packages.

Please look back at this and designate this repository as a template, as you obviously created it to be one.

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

**Comment by gep13** [comment]
I ticked the box to make this a template repository.

Think we can go ahead and close this issue out.
