### ISSUE TITLE
Missing steps in AU setups

### ISSUE THREAD

**Issue by lackovic** [chocolatey-community/chocolatey-packages-template#33]
Following the AU setup steps for the first time in [setup/README.md](https://github.com/chocolatey-community/chocolatey-packages-template/blob/master/setup/README.md) I ran into some unsatisfied requirements. I added them in [this PR](https://github.com/chocolatey-community/chocolatey-packages-template/pull/32).

**Comment by ferventcoder** [comment]
Thanks for the PR and like @pauby mentioned, sorry it took so long to review it!
