### ISSUE TITLE
Contribute ability for before update / post update scripts to be considered as Ketarin job failures with switches

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey-community/chocolatey-packages-template#4]
This would be great.

Like a little box under each to make them failures when they exit non-zero.

**Comment by ferventcoder** [comment]
cc @dtgm

**Comment by gep13** [comment]
This template repository no longer makes use of Ketarin, and instead uses Chocolatey-AU, so I think we can go ahead and close this out.
