### ISSUE TITLE
The exe file Is not copied from the source url to the package folder during installation.

### ISSUE THREAD

**Issue by moh-hassan** [chocolatey-community/chocolatey-packages-template#40]
I created a package for exe application (exe is not a setup program, it is xcopy) like the template
https://github.com/chocolatey-community/chocolatey-packages-template/tree/master/automatic/1password

Then test the package using the command 
Test-Package -Install  
and pass ok, then I pushed the package to chocolatey site.

When Installing the package by the command:
choco install  odata2poco-commandline

I expect that the exe file will be copied to the package location during the installation, but really the exe not copied  and the package is not working.

What I missed to resolve the package installation and enable copying the exe as is on the package folder
[odata2poco-commandline.4.3.1.nupkg.zip](https://github.com/chocolatey-community/chocolatey-packages-template/files/9313242/odata2poco-commandline.4.3.1.nupkg.zip)
The package is attached.

**Comment by pauby** [comment]
This isn't the right place for this issue. Can I suggest you reach out to the community via [Discord](https://ch0.co/community) or [Google Groups](https://groups.google.com/forum/#!forum/chocolatey)?
