### ISSUE TITLE
Kindle update Mochi to newest version

### ISSUE THREAD

**Issue by aadimator** [chocolatey-community/chocolatey-packages-template#41]
Can you kindly update `mochi` package to the newest version? Currently, the available version is `1.14.7`.

Thanks

**Comment by gep13** [comment]
Can I ask what brought you to this repository to raise this issue?  No packages are maintained in this repository.

I would suggest that you reach out to the package maintainer, which you can find on this page:

https://community.chocolatey.org/packages/mochi
